#! /bin/bash

fn=("alabama"
'alaska'
'arizona'
'arkansas'
'california'
'colorado'
'connecticut'
'delaware'
'florida'
'georgia'
'hawaii'
'idaho'
'illinois'
'indiana'
'iowa'
'kansas'
'kentucky'
'louisiana'
'maine'
'maryland'
'massachusetts'
'michigan'
'minnesota'
'mississippi'
'missouri'
'montana'
'nebraska'
'nevada'
'new_hampshire'
'new_jersey'
'new_mexico'
'new_york'
'north_carolina'
'north_dakota'
'ohio'
'oklahoma'
'oregon'
'pennsylvania'
'rhode_island'
'south_carolina'
'south_dakota'
'tennessee'
'texas'
'utah'
'vermont'
'virginia'
'washington'
'west_virginia'
'wisconsin'
'wyoming')



for i in "${fn[@]}"
do
  wget "http://www.50states.com/maps/$i.gif"
done
